version: "3.9"

services:
  # --- Database ---
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      PGDATA: /data/postgres
    volumes:
      - ms_insurance_data:/data/postgres
    ports:
      - ${DB_PORT}:5432

volumes:
  ms_insurance_data:
